stages:
  get_data:
    cmd: python src/get_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - data_given/mushrooms.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data_given/mushrooms.csv
    outs:
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv

  data_preprocess:
    cmd: python src/data_preprocess.py --config=params.yaml
    deps:
    - src/data_preprocess.py
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv
    outs:
    - data/encoder/train_encoded_mushrooms.csv
    - data/encoder/test_encoded_mushrooms.csv
    
  model:
    cmd: python src/model.py  --config=params.yaml
    deps:
    - src/model.py
    - data/encoder/train_encoded_mushrooms.csv
    - data/encoder/test_encoded_mushrooms.csv
    params:
    - estimator.SVC.params.cache_size
    - estimator.SVC.params.degree
    metrics:
    - reports/reports.csv
    outs:
    - models/model.pkl